### ISSUE TITLE
Actual temperature not displayed

### ISSUE THREAD

**Issue by stefanvaduva** [Juerd/eq3-max#13]
Hello! Is there anything special I need to do in order to have the actual temperature (not the target one) displayed? I currently get 0.0 for all zones. 

<img width="665" alt="Screenshot 2021-12-04 at 18 32 54" src="https://user-images.githubusercontent.com/535905/144717103-235485b6-3206-4bed-845a-deef85cdbd8d.png">

**Comment by Juerd** [comment]
Stefan skribis 2021-12-04  8:34 (-0800):
>Hello! Is there anything special I need to do in order to have the actual temperature (not the target one) displayed? I currently get 0.0 for all zones.

Note that the current temperature is not reported by radiator valves, so you need a room thermostat for that. This is a hardware limitation.

**Comment by stefanvaduva** [comment]
Ah, sorry, I thought that the L message contains the temperature for TRVs as well and I was hoping that there is something I need to do in order to activate the display. 

Thanks for this really useful tool! I was really close to ditching my EQ3 system, but now that I've found this, I'll keep it and fiddle with it.
