### ISSUE TITLE
boiler control tuning question 

### ISSUE THREAD

**Issue by rossbeazley** [Juerd/eq3-max#19]
Regards https://github.com/Juerd/eq3-max/blob/daa4aadca7c3046da50c4bddaa906b5d0dc5db32/lib/Max.pm#L335-L344

How did you come to the number 60? How many devices would you expect in a deployment?

I have eleven so I think this 60 threshold might get hit often and I'm considering tuning this value

Thanks!

**Comment by Juerd** [comment]
The number is completely arbitrary. The idea behind this check is to avoid enabling the boiler when the circuit is blocked (no water can be pumped). The main logic of the function is the initial assignment of $demand, based on whether there's any room that is colder than its setpoint.

**Comment by rossbeazley** [comment]
Ah, got you, I've barely written any perl in the last thirty years. So the statement will reset demand to 0 unless enough "valve" is open in the circuit. Thanks for helping
