### ISSUE TITLE
Connect: IO::Socket::INET: connect: timeout at Max.pm line 54 on Mac OSX 

### ISSUE THREAD

**Issue by meirion** [Juerd/eq3-max#3]
Hi,

I've downloaded the Git repo and trying to run on Mac OS X:

`$ ./max
Found cube at 192.168.0.29
Connect: IO::Socket::INET: connect: timeout at /Users/meirion.williams/Documents/juerdmax/opt/eq3-max/bin/../lib/Max.pm line 54.
$ ./max dump
Found cube at 192.168.0.29
Connect: IO::Socket::INET: connect: timeout at /Users/meirion.williams/Documents/juerdmax/opt/eq3-max/bin/../lib/Max.pm line 54.
$ ./max status
Found cube at 192.168.0.29
Connect: IO::Socket::INET: connect: timeout at /Users/meirion.williams/Documents/juerdmax/opt/eq3-max/bin/../lib/Max.pm line 54.
`
Any idea?

**Comment by Juerd** [comment]
That's a connection issue. Could be related to firewall settings, but it can also be that your cube has crashed. Another option is that 192.168.0.29 is not reachable but your router doesn't pass the icmp error message.

**Comment by meirion** [comment]
Thanks. Was taken aback by the error message really.

Running on Windows seems more stable for me.
