### ISSUE TITLE
Question: battery-status and window-detection-status

### ISSUE THREAD

**Issue by Sen5ation** [Juerd/eq3-max#4]
Hi,

i havent tested your script yet. 
I guess i have to buy an eqMAX-set first, but i have a question in advance:

- Is the battery-status of thermostates and windows-detector  included when you run the status command? 
- Is the windows-detector-status included when you run the status command?
- If not: is it planned? 

I'm looking for a great way to implement the eqMAX-stuff into my homeautomatic system which i scripted myself on several raspberry pis.

**Comment by Juerd** [comment]
Sen5ation skribis 2018-10-10  4:07 (-0700):
> - Is the battery-status of thermostates and windows-detector  included
> when you run the status command? 

Probably, but I don't have any window switch.

> - Is the windows-detector-status included when you run the status command?
> - If not: is it planned? 

I don't have any of the window thingies and don't plan to buy them. I'll
happily write support for them if someone donates one :)

If you happen to be a programmer, you could consider writing the support
for the window switch yourself and sending me a pull request.
