### ISSUE TITLE
set room temperature sets temperature for all rooms?

### ISSUE THREAD

**Issue by Sen5ation** [Juerd/eq3-max#7]
Hi,

i got a cube and 2 radiators and 2 windows detectors now .
I have 2 rooms setup with the IDs 1 and 2.
I run the command "max set room 2 21". 
Not only room 2 **but also** room 1 got now the temperature 21 degres. 
Why is that? Can you reproduce that?

**Comment by servidge** [comment]
Same setup here and it worked fine.
The command should be "max set 2 21" if you want to set room number 2 to 21 degree. With your input "max set room 2 21" perl should give error messages.

**Comment by Sen5ation** [comment]
Hmm, I deleted all rooms on the maxcube all thought it seems all good.
Now it does what it should do.
Thanks for your time ;)
